const bcpFactionMap = {
    "Steelheart's Champions": "Steelheart's Champions",
    "Garrek's Reavers": "Garrek's Reavers",
    "Ironskulls Boyz": "Ironskull's Boyz",
    'The Sepulchral Guard': 'Sepulchral Guard',
    'The Chosen Axes': 'Chosen Axes',
    "Spiteclaw's Swarm": "Spiteclaw's Swarm",
    "Magore’s Fiends": "Magore's Fiends",
    "The Farstriders": 'Farstriders',
    "Stormsire's Cursebreakers": "Stormsire's Cursebreakers",
    "Thorns of the Briar Queen": 'Thorns of the Briar Queen',
    "Zarbag’s Gitz": "Zarbag's Gitz",
    "Eyes of the Nine": 'Eyes of the Nine',
    "The Eyes of the Nine": 'Eyes of the Nine',
    "Godsworn's Hunt": 'Godsworn Hunt',
    "The Godsworn Hunt": 'Godsworn Hunt',
    "Mollog's Mob": "Mollog's Mob",
    "Ylthari’s Guardians": "Ylthari's Guardians",
    "Thundrik’s Profiteers": "Thundrik's Profiteers",
    "Grashrak’s Despoilers": "Grashrak's Despoilers",
    "Skaeth’s Wild Hunt": "Skaeth's Wild Hunt",
    "Ironsoul’s Condemnors": "Ironsoul's Condemners",
    "Lady Harrow’s Mournflight": "Lady Harrow's Mournflight",
    "The Grymwatch": 'Grymwatch',
    "Rippa's Snarlfangs": "Rippa's Snarlfangs",
    "Hrothgorn's Mantrappers": "Hrothgorn's Mantrappers",
    "The Wurmspat": 'Wurmspat',
    "Morgok’s Krushas": "Morgok's Krushas",
    "Morgwaeth’s Blade-coven": "Morgwaeth's Blade coven",
    "Myari's Purifiers": "Myari's Purifiers",
    "The Dread Pageant": 'Dread Pageant',
    "Khagra's Ravagers": "Khagra's Ravagers",
    "Starblood Stalkers": 'Starblood Stalkers',
    "The Starblood Stalkers": 'Starblood Stalkers',
    "The Crimson Court": 'Crimson Court',
    "Storm of Celestus": 'Storm of Celestus',
    "The Storm of Celestus": 'Storm of Celestus',
    'Drepur’s Wraithcreepers': "Drepur's Wraithcreepers",
    "Hedrakka’s MadMob": "Hedkrakka's Madmob",
    "Kainan’s Reapers": "Kainan's Reapers",
    "Elathain’s Soulraid": "Elathain's Soulraid",
    "Xandire's Truthseekers": "Xandire's Truthseekers",
    "Da Kunnin Krew": "Da Kunnin' Krew",
    "Blackpowder's Buccaneers": "Blackpowder's Buccaneers",
    "The Exiled Dead": 'Exiled Dead',
    "The Shadeborn": 'Shadeborn',
    "Skittershanks's Clawpack": "Skittershank's Clawpack",
    "Skittershank's Clawpack": "Skittershank's Clawpack",
    "Hexbane's Hunters": "Hexbane's Hunters",
    "Gorechosen of Dromm": 'Gorechosen of Dromm',
    "The Gnarlspirit Pack": 'Gnarlspirit Pack',
    "The Sons of Velmorn": 'Sons of Velmorn',
    "Grinkrak's Looncourt": "Grinkrak's Looncourt",
    "Gryselle's Arenai": "Gryselle's Arenai",
    "Domitan's Stormcoven": "Domitan's Stormcoven",
    "Ephilim's Pandaemonium": "Ephilim's Pandaemonium",
    "The Headsmen's Curse": "Headsmen's Curse",
    "Skabbik's Plaguepack": "Skabbik's Plaguepack",
    "The Thricefold Discord": 'Thricefold Discord',
    "Cyreni's Razors": "Cyreni's Razors",
    "Daggok's Stab-Ladz": "Daggok's Stab-ladz",
    "Zondara's Gravebreakers": "Zondara's Gravebreakers",
    'Brethren of the Bolt': 'Brethren of the Bolt',
    'Skinnerkin': 'Skinnerkin',
    "The Emberwatch": 'Emberwatch',
    "Zikkit's Tunnelpack": "Zikkit's Tunnelpack",
    "Grandfather's Gardeners": "Grandfather's Gardeners",
    "Jaws of Itzl": 'Jaws of Itzl',
    "Borgit's Beastgrabbaz": "Borgit's Beastgrabbaz",
    'Knives of the Crone': 'Knives of the Crone',
    "Kamandora's Blades": "Kamandora's Blades"
}

// These are the abbreviations used by underworldsdb in their deck sharing URL
const deckMap = {
    'CC': 'Countdown to Cataclysm',
    'PL': 'Pillage and Plunder',
    'BL': 'Blazing Assault',
    'ES': 'Emberstone Sentinels',
    'WR': 'Wrack and Ruin',
    'EK': 'Edge of the Knife',
    'RF': 'Reckless Fury',
    'RS': 'Realmstone Raiders',
    'RG': 'Raging Slayers'
}

const bcpBaseUrl = 'https://newprod-api.bestcoastpairings.com'
const bcpPairingsEndpoint = '/v1/pairings?limit=500&pairingType=Pairing&expand%5B%5D=player1&expand%5B%5D=player2&expand%5B%5D=player1Game&expand%5B%5D=player2Game&eventId='
const bcpPlayersEndpoint = '/v1/players?limit=100&eventId='
const bcpDecklistBaseUrl = '/v1/armylists/'

const bcpFrontBase = 'https://bestcoastpairings.com'

export { bcpFactionMap, deckMap, bcpBaseUrl, bcpPairingsEndpoint, bcpPlayersEndpoint, bcpDecklistBaseUrl, bcpFrontBase }
