export const countries = {
    'Afghanistan': 'AFG',
    'Albania': 'ALB',
    'Algeria': 'DZA',
    'Andorra': 'AND',
    'Angola': 'AGO',
    'Antigua and Barbuda': 'ATG',
    'Argentina': 'ARG',
    'Armenia': 'ARM',
    'Australia': 'AUS',
    'Austria': 'AUT',
    'Azerbaijan': 'AZE',
    'Bahamas': 'BHS',
    'Bahrain': 'BHR',
    'Bangladesh': 'BGD',
    'Barbados': 'BRB',
    'Belarus': 'BLR',
    'Belgium': 'BEL',
    'Belize': 'BLZ',
    'Benin': 'BEN',
    'Bhutan': 'BTN',
    'Bolivia': 'BOL',
    'Bosnia and Herzegovina': 'BIH',
    'Botswana': 'BWA',
    'Brazil': 'BRA',
    'Brunei': 'BRN',
    'Bulgaria': 'BGR',
    'Burkina Faso': 'BFA',
    'Burundi': 'BDI',
    'Cambodia': 'KHM',
    'Cameroon': 'CMR',
    'Canada': 'CAN',
    'Cape Verde': 'CPV',
    'Central African Republic': 'CAF',
    'Chad': 'TCD',
    'Chile': 'CHL',
    'China': 'CHN',
    'Colombia': 'COL',
    'Comoros': 'COM',
    'Costa Rica': 'CRI',
    'Croatia': 'HRV',
    'Cuba': 'CUB',
    'Cyprus': 'CYP',
    'Czechia': 'CZE',
    'Denmark': 'DNK',
    'Djibouti': 'DJI',
    'Dominica': 'DMA',
    'Dominican Republic': 'DOM',
    'DR Congo': 'COD',
    'Ecuador': 'ECU',
    'Egypt': 'EGY',
    'El Salvador': 'SLV',
    'Equatorial Guinea': 'GNQ',
    'Eritrea': 'ERI',
    'Estonia': 'EST',
    'Eswatini': 'SWZ',
    'Ethiopia': 'ETH',
    'Fiji': 'FJI',
    'Finland': 'FIN',
    'France': 'FRA',
    'Gabon': 'GAB',
    'Gambia': 'GMB',
    'Georgia': 'GEO',
    'Germany': 'DEU',
    'Ghana': 'GHA',
    'Greece': 'GRC',
    'Grenada': 'GRD',
    'Guatemala': 'GTM',
    'Guinea': 'GIN',
    'Guinea-Bissau': 'GNB',
    'Guyana': 'GUY',
    'Haiti': 'HTI',
    'Honduras': 'HND',
    'Hong Kong': 'HKG',
    'Hungary': 'HUN',
    'Iceland': 'ISL',
    'India': 'IND',
    'Indonesia': 'IDN',
    'Iran': 'IRN',
    'Iraq': 'IRQ',
    'Ireland': 'IRL',
    'Israel': 'ISR',
    'Italy': 'ITA',
    'Ivory Coast': 'CIV',
    'Jamaica': 'JAM',
    'Japan': 'JPN',
    'Jordan': 'JOR',
    'Kazakhstan': 'KAZ',
    'Kenya': 'KEN',
    'Kiribati': 'KIR',
    'Kuwait': 'KWT',
    'Kyrgyzstan': 'KGZ',
    'Laos': 'LAO',
    'Latvia': 'LVA',
    'Lebanon': 'LBN',
    'Lesotho': 'LSO',
    'Liberia': 'LBR',
    'Libya': 'LBY',
    'Liechtenstein': 'LIE',
    'Lithuania': 'LTU',
    'Luxembourg': 'LUX',
    'Madagascar': 'MDG',
    'Malawi': 'MWI',
    'Malaysia': 'MYS',
    'Maldives': 'MDV',
    'Mali': 'MLI',
    'Malta': 'MLT',
    'Marshall Islands': 'MHL',
    'Mauritania': 'MRT',
    'Mauritius': 'MUS',
    'Mexico': 'MEX',
    'Micronesia': 'FSM',
    'Moldova': 'MDA',
    'Monaco': 'MCO',
    'Mongolia': 'MNG',
    'Montenegro': 'MNE',
    'Morocco': 'MAR',
    'Mozambique': 'MOZ',
    'Myanmar': 'MMR',
    'Namibia': 'NAM',
    'Nauru': 'NRU',
    'Nepal': 'NPL',
    'Netherlands': 'NLD',
    'Nicaragua': 'NIC',
    'Niger': 'NER',
    'Nigeria': 'NGA',
    'North Macedonia': 'MKD',
    'Norway': 'NOR',
    'Oman': 'OMN',
    'Pakistan': 'PAK',
    'Palau': 'PLW',
    'Panama': 'PAN',
    'Papua New Guinea': 'PNG',
    'Paraguay': 'PRY',
    'Peru': 'PER',
    'Philippines': 'PHL',
    'Poland': 'POL',
    'Portugal': 'PRT',
    'Qatar': 'QAT',
    'Republic of the Congo': 'COD',
    'Romania': 'ROU',
    'Russia': 'RUS',
    'Samoa': 'WSM',
    'San Marino': 'SMR',
    'Sao Tome and Principe': 'STP',
    'Saudi Arabia': 'SAU',
    'Senegal': 'SEN',
    'Serbia': 'SRB',
    'Seychelles': 'SYC',
    'Sierra Leone': 'SLE',
    'Singapore': 'SGP',
    'Slovakia': 'SVK',
    'Slovenia': 'SVN',
    'Somalia': 'SOM',
    'South Africa': 'ZAF',
    'South Korea': 'KOR',
    'South Sudan': 'SSD',
    'Spain': 'ESP',
    'Sri Lanka': 'LKA',
    'Sudan': 'SDN',
    'Suriname': 'SUR',
    'Sweden': 'SWE',
    'Switzerland': 'CHE',
    'Syria': 'SYR',
    'Tajikistan': 'TJK',
    'Tanzania': 'TZA',
    'Thailand': 'THA',
    'Timor-Leste': 'TLS',
    'Togo': 'TGO',
    'Tonga': 'TON',
    'Tunisia': 'TUN',
    'Turkey': 'TUR',
    'Turkmenistan': 'TKM',
    'Tuvalu': 'TUV',
    'Uganda': 'UGA',
    'Ukraine': 'UKR',
    'United Arab Emirates': 'ARE',
    'United Kingdom': 'GBR',
    'United States': 'USA',
    'Uruguay': 'URY',
    'Uzbekistan': 'UZB',
    'Vanuatu': 'VUT',
    'Venezuela': 'VEN',
    'Vietnam': 'VNM',
    'Yemen': 'YEM',
    'Zambia': 'ZMB',
    'Zimbabwe': 'ZWE',
    'República de Angola (a)': 'AGO',
    'República Argentina (la)': 'ARG',
    'Republik Österreich (die)': 'AUT',
    'Azǝrbaycan Respublikası': 'AZE',
    'Commonwealth of the Bahamas (The)': 'BHS',
    'مملكة البحرين - Mamlakat al Bahrayn': 'BHR',
    'গণপ্রজাতন্ত্রী বাংলাদেশ - Gaṇaprajātantrī Bāṁlādesh': 'BGD',
    'Рэспубліка Беларусь - Respublika Bielaruś': 'BLR',
    'Koninkrijk België (het)': 'BEL',
    'la République du Bénin': 'BEN',
    'Druk Gyalkhap': 'BTN',
    'Estado Plurinacional de Bolivia (el)': 'BOL',
    'Republic of Botswana (The)': 'BWA',
    'República Federativa do Brasil (a)': 'BRA',
    'Република България - Republika Bulgaria': 'BGR',
    'Burkina Faso (le)': 'BFA',
    'République du Burundi (la)': 'BDI',
    'Preăhréachéanachâkr Kâmpŭchéa': 'KHM',
    'Republic of Cameroon (The)': 'CMR',
    'República de Cabo Verde (a)': 'CPV',
    'جمهورية تشاد - Jumhuriyat Tshad': 'TCD',
    'República de Chile (la)': 'CHL',
    'Zhonghua Renmin Gongheguo': 'CHN',
    'República de Colombia (la)': 'COL',
    'اتحاد جزر القمر - Ittihad al Qamar': 'COM',
    'República de Costa Rica (la)': 'CRI',
    'Republika Hrvatska': 'HRV',
    'República de Cuba (la)': 'CUB',
    'Κυπριακή Δημοκρατία - Kypriakí Dimokratía': 'CYP',
    'Česká republika': 'CZE',
    'Kongeriget Danmark': 'DNK',
    'جمهورية جيبوتي - Jumhuriyat Jibuti': 'DJI',
    'Commonwealth of Dominica (The)': 'DMA',
    'República Dominicana (la)': 'DOM',
    'República del Ecuador (la)': 'ECU',
    'República de El Salvador (la)': 'SLV',
    'République de Guinée équatoriale (la)': 'GNQ',
    'إريتريا - Dawlat Iritriya': 'ERI',
    'Eesti Vabariik': 'EST',
    'Kingdom of Eswatini (The)': 'SWZ',
    'Republic of the Fiji Islands (The)': 'FJI',
    'Suomen tasavalta': 'FIN',
    'République française (la)': 'FRA',
    'République gabonaise (la)': 'GAB',
    'Islamic Republic of The Gambia (The)': 'GMB',
    'Bundesrepublik Deutschland (die)': 'DEU',
    'Republic of Ghana (The)': 'GHA',
    'Ελληνική Δημοκρατία - Ellinikí Dimokratía': 'GRC',
    'República de Guatemala (la)': 'GTM',
    'République de Guinée (la)': 'GIN',
    'República da Guiné-Bissau (a)': 'GNB',
    'Republic of Guyana (The)': 'GUY',
    'República de Honduras (la)': 'HND',
    'Lýðveldið Ísland': 'ISL',
    'Republic of India (The)': 'IND',
    'Republik Indonesia': 'IDN',
    'جُمْهُورِئ إِسْلامِئ إِيرَان - Jomhuri-ye Eslāmi-ye Irān': 'IRN',
    'Repubblica Italiana (la)': 'ITA',
    'Nihon-koku or Nippon-koku': 'JPN',
    'المملكة الأردنية الهاشمية - Al Mamlakah al Urdunīyah al Hāshimīyah': 'JOR',
    'Қазақстан Республикасы - Qazaqstan Respūblīkasy': 'KAZ',
    'Republic of Kenya (The)': 'KEN',
    'Republic of Kiribati (The)': 'KIR',
    'دولة الكويت - Dawlat al Kuwayt': 'KWT',
    'Кыргыз Республикасы - Kyrgyz Respublikasy': 'KGZ',
    'Sathalanalat Paxathipatai Paxaxôn Lao': 'LAO',
    'Latvijas Republika': 'LVA',
    'الجمهورية اللبنانية - Al Jumhūrīyah al Lubnānīyah': 'LBN',
    'Kingdom of Lesotho (The)': 'LSO',
    'Republic of Liberia (The)': 'LBR',
    'ليبيا - Lībyā': 'LBY',
    'Fürstentum Liechtenstein (das)': 'LIE',
    'Lietuvos Respublika': 'LTU',
    'Grand-Duché de Luxembourg (le)': 'LUX',
    'République de Madagascar (la)': 'MDG',
    'Dziko la Malaŵi': 'MWI',
    'ދިވެހިރާއްޖޭގެ ޖުމުހޫރިއްޔާ - Dhivehi Raajjeyge Jumhooriyyaa': 'MDV',
    'République du Mali (la)': 'MLI',
    'Republic of Malta (The)': 'MLT',
    'Republic of The Marshall Islands (The)': 'MHL',
    'الجمهورية الإسلامية الموريتانية - Al Jumhūrīyah al Islāmīyah al Mūrītānīyah': 'MRT',
    'Republic of Mauritius (The)': 'MUS',
    'Estados Unidos Mexicanos (Los)': 'MEX',
    'Federated States of Micronesia (The)': 'FSM',
    'Republica Moldova': 'MDA',
    'Principauté de Monaco (la)': 'MCO',
    'Монгол улс| - Mongol uls': 'MNG',
    'Црна Гора - Crna Gora': 'MNE',
    'المملكة المغربية - Al Mamlakah al Maghribīyah': 'MAR',
    'República de Moçambique (a)': 'MOZ',
    'Pyidaungzu Thammada Myanma Naingngandaw': 'MMR',
    'Republic of Namibia (The)': 'NAM',
    'Republic of Nauru (The)': 'NRU',
    'संघीय लोकतान्त्रिक गणतन्त्र नेपाल - Saṁghīya Loktāntrik Gaṇatantra Nepāl': 'NPL',
    'Koninkrijk der Nederlanden (het)': 'NLD',
    'New Zealand': 'NZL',
    'República de Nicaragua (la)': 'NIC',
    'République du Niger (la)': 'NER',
    'Federal Republic of Nigeria (The)': 'NGA',
    'Поранешна Jугословенска Република Македониjа - Poranešna Jugoslovenska Republika Makedonija': 'MKD',
    'Kongeriket Norge': 'NOR',
    'Islamic Republic of Pakistan (The)': 'PAK',
    'Republic of Palau (The)': 'PLW',
    'República de Panamá (la)': 'PAN',
    'Independent State of Papua New Guinea': 'PNG',
    'Paraguay Retãn': 'PRY',
    'República del Perú (la)': 'PER',
    'Republic of the Philippines (The)': 'PHL',
    'Rzeczpospolita Polska': 'POL',
    'República Portuguesa (a)': 'PRT',
    'دولة قطر - Dawlat Qaţar': 'QAT',
    'République du Congo (la)': 'COD',
    'România': 'ROU',
    'Российская Федерация - Rossijskaja Federacija': 'RUS',
    'Saint Kitts and Nevis': 'KNA',
    'Saint Lucia': 'LCA',
    'Saint Vincent and the Grenadines': 'VCT',
    'Independent State of Samoa (The)': 'WSM',
    'Repubblica di San Marino (la)': 'SMR',
    'República Democrática de São Tomé e Príncipe (a)': 'STP',
    'République du Sénégal (la)': 'SEN',
    'Република Србија': 'SRB',
    'Repiblik Sesel': 'SYC',
    'Republic of Sierra Leone {The}': 'SLE',
    'Xinjiapo Gongheguo': 'SGP',
    'Slovenská republika': 'SVK',
    'Republika Slovenija': 'SVN',
    'Solomon Islands': 'SLB',
    'جمهورية الصومال الاتحادية - Jumhūriyyat aş Şūmāl al Fidirāliyyah': 'SOM',
    'Republiek van Suid-Afrika': 'ZAF',
    'Daehanminguk': 'KOR',
    'Republic of South Sudan (The)': 'SSD',
    'Reino de España (el)': 'ESP',
    'Shrī Lamkā Prajātāntrika Samājavā dī Janarajaya': 'LKA',
    'جمهورية السودان - Jumhūrīyat as Sūdān': 'SDN',
    'Republiek Suriname (de)': 'SUR',
    'Konungariket Sverige': 'SWE',
    'Confédération suisse (la)': 'CHE',
    'Ҷумҳурии Тоҷикистон - Jumhurii Tojikiston': 'TJK',
    'United Republic of Tanzania (The)': 'TZA',
    'ราชอาณาจักรไทย - Ratcha Anachak Thai': 'THA',
    'Poranešna Jugoslovenska Republika Makedonija': 'TLS',
    'République togolaise (la)': 'TGO',
    'Puleʻanga Tonga': 'TON',
    'الجمهورية التونسية - Al Jumhūrīyah at Tūnisīyah': 'TUN',
    'Türkiye Cumhuriyeti': 'TUR',
    'Türkmenistan': 'TKM',
    'Republic of Uganda (The)': 'UGA',
    'Украïна - Ukraina': 'UKR',
    'United States of America (The)': 'USA',
    'República Oriental del Uruguay (la)': 'URY',
    'Ripablik blong Vanuatu': 'VUT',
    'República Bolivariana de Venezuela (la)': 'VEN',
    'Cộng Hòa Xã Hội Chủ Nghĩa Việt Nam': 'VNM',
    'الجمهورية اليمنية - Al Jumhūrīyah al Yamanīyah': 'YEM',
    'Republic of Zambia (The)': 'ZMB',
    'Republic of Zimbabwe (The)': 'ZWE',
    'أَفْغَانِسْتَان - Afghanestan': 'AFG',
    'Shqipëri/Shqipëria': 'ALB',
    'Argentina (la)': 'ARG',
    'Հայաստան - Hayastan': 'ARM',
    'Österreich': 'AUT',
    'Azǝrbaycan': 'AZE',
    'Bahamas (The)': 'BHS',
    'البحرين - Al Bahrayn': 'BHR',
    'বাংলাদেশ - Bāṁlādesh': 'BGD',
    'Беларусь - Bielaruś': 'BLR',
    'België': 'BEL',
    'Bénin (le)': 'BEN',
    'Druk yul': 'BTN',
    'Bosna i Hercegovina': 'BIH',
    'Brasil (o)': 'BRA',
    'Brunei Darussalam': 'BRN',
    'България - Bulgaria': 'BGR',
    'Burkina (le)': 'BFA',
    'Burundi (le)': 'BDI',
    'Kâmpŭchéa': 'KHM',
    'Cabo Verde': 'CPV',
    'République centrafricaine (la)': 'CAF',
    'تشاد - Tshad': 'TCD',
    'Zhongguo': 'CHN',
    'جزر القمر - Al Qamar': 'COM',
    'Hrvatska': 'HRV',
    'Κύπρος - Kýpros': 'CYP',
    'Česko': 'CZE',
    'Danmark': 'DNK',
    'جيبوتي - Jibuti': 'DJI',
    'Dominicana (la)': 'DOM',
    'République démocratique du Congo (la)': 'COD',
    'Ecuador (el)': 'ECU',
    'مصر - Mişr': 'EGY',
    'Guinée équatoriale (la)': 'GNQ',
    'إريتريا - Iritriya': 'ERI',
    'Eesti': 'EST',
    'Suomi': 'FIN',
    'France (la)': 'FRA',
    'Gabon (le)': 'GAB',
    'Gambia (The)': 'GMB',
    'Deutschland': 'DEU',
    'Ελλάς - Ellás': 'GRC',
    'Guinée (la)': 'GIN',
    'Guiné-Bissau': 'GNB',
    'Haïti': 'HTI',
    'Magyarország': 'HUN',
    'Ísland': 'ISL',
    'إِيرَان - Irān': 'IRN',
    'Nihon or Nippon': 'JPN',
    'الأردن - Al Urdun': 'JOR',
    'Қазақстан - Qazaqstan': 'KAZ',
    'الكويت - Al Kuwayt': 'KWT',
    'Кыргызстан - Kyrgyzstan': 'KGZ',
    'Latvija': 'LVA',
    'لبنان - Lubnān': 'LBN',
    'Lietuva': 'LTU',
    'Luxembourg (le)': 'LUX',
    'Madagascar [fém.]': 'MDG',
    'Malaŵi': 'MWI',
    'ގުޖޭއްރާ ޔާއްރިހޫމްޖު - Dhivehi Raajje': 'MDV',
    'Mali (le)': 'MLI',
    'Marshall Islands (The)': 'MHL',
    'موريتانيا - Mūrītānīya': 'MRT',
    'México': 'MEX',
    'Monaco [masc.]': 'MCO',
    'Монгол| - Mongol': 'MNG',
    'المغرب - Al Maghrib': 'MAR',
    'Moçambique': 'MOZ',
    'Myanma': 'MMR',
    'नेपाल - Nepāl': 'NPL',
    'Nederland': 'NLD',
    'Norge': 'NOR',
    'Panamá': 'PAN',
    'Perú': 'PER',
    'Philippines (The)': 'PHL',
    'Polska': 'POL',
    'قطر - Qaţar': 'QAT',
    'Congo (le)': 'COD',
    'Российская Федерация - Rossija': 'RUS',
    'São Tomé e Príncipe': 'STP',
'Sénégal (le)': 'SEN',
    'Србија - Srbija': 'SRB',
    'Sesel': 'SYC',
    'Xinjiapo': 'SGP',
    'Slovensko': 'SVK',
    'Slovenija': 'SVN',
    'اَلصُّومَال - Aş Şūmāl': 'SOM',
    'Suid-Afrika': 'ZAF',
    'Hanguk': 'KOR',
    'España': 'ESP',
    'Shrī Lamkā': 'LKA',
    'السودان - As Sūdān': 'SDN',
    'Sverige': 'SWE',
    'Suisse (la)': 'CHE',
    'الجمهورية العربية السورية - Sūrīyah': 'SYR',
    'Тоҷикистон - Tojikiston': 'TJK',
    'ประเทศไทย - PraThet Thai': 'THA',
    'Togo (le)': 'TGO',
    'تونس - Tūnis': 'TUN',
    'Türkiye': 'TUR',
    'الإمارات العربية المتحدة - Al Imārāt': 'ARE',
    'United Kingdom of Great Britain and Northern Ireland (The)': 'GBR',
    'Uruguay (el)': 'URY',
    'Venezuela (República Bolivariana de)': 'VEN',
    'Việt Nam': 'VNM',
    'اليمن - Al Yaman': 'YEM',
    'Australia[b]': 'AUS',
    'Bahamas (the)': 'BHS',
    'Bolivia (Plurinational State of)': 'BOL',
    'Brunei Darussalam[e]': 'BRN',
    'Central African Republic (the)': 'CAF',
    'Comoros (the)': 'COM',
    'Czechia[i]': 'CZE',
    'Dominican Republic (the)': 'DOM',
    'Eswatini[j]': 'SWZ',
    'France[l]': 'FRA',
    'Gambia (the)': 'GMB',
    'Iran (Islamic Republic of)[o]': 'IRN',
    'Marshall Islands (the)': 'MHL',
    'Micronesia (Federated States of)': 'FSM',
    'Moldova (the Republic of)': 'MDA',
    'Myanmar[t]': 'MMR',
    'Netherlands (Kingdom of the)': 'NLD',
    'Niger (the)': 'NER',
    'North Macedonia[u]': 'MKD',
    'Philippines (the)': 'PHL',
    'Congo': 'COD',
    'Russian Federation (the)[w]': 'RUS',
    'Rwanda': 'RWA',
    'Korea': 'KOR',
    'Sudan (the)': 'SDN',
    'Syrian Arab Republic (the)[y]': 'SYR',
    'Tanzania, the United Republic of': 'TZA',
    'Timor-Leste[ab]': 'TLS',
    'Türkiye[ac]': 'TUR',
    'Ukraine[ad]': 'UKR',
    'United Arab Emirates (the)': 'ARE',
    'United Kingdom of Great Britain and Northern Ireland (the)': 'GBR',
    'United States of America (the)': 'USA',
    'Venezuela (Bolivarian Republic of)': 'VEN',
    'Viet Nam[ah]': 'VNM',
    'UK': 'GBR',
    'GB': 'GBR',
    'ES': 'ESP'
}
